// docs/design/mockup/components-erp/erp-shell.tsx
'use client'

import { useState, useSyncExternalStore } from 'react'
import { useTheme } from 'next-themes'
import { motion } from 'framer-motion'
import { Button } from '@/components/ui/button'
import { Avatar, AvatarFallback } from '@/components/ui/avatar'
import { Separator } from '@/components/ui/separator'
import { Sheet, SheetContent, SheetTitle, SheetTrigger } from '@/components/ui/sheet'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu'
import { cn } from '@/lib/utils'
import { DashboardView } from './dashboard-view'
import { SalesView } from './sales-view'
import { InventoryView } from './inventory-view'
import { FinanceView } from './finance-view'
import { HrView } from './hr-view'
import { ReportsView } from './reports-view'
import { SettingsView } from './settings-view'
import {
  LayoutDashboard,
  ShoppingCart,
  Boxes,
  Banknote,
  UsersRound,
  FileBarChart2,
  Settings,
  Search,
  Menu,
  HelpCircle,
  ChevronsUpDown,
  LogOut,
  UserCog,
  Sun,
  Moon,
  PenTool,
  Share2,
} from 'lucide-react'
import { CommandPalette } from './command-palette'
import { NotificationCenter } from './notification-center'
import { UserProfileDialog } from './user-profile-dialog'
import { ShareDialog } from './share-dialog'
import type { ErpNotification } from '@/lib/erp-data'

type ViewId = 'dashboard' | 'sales' | 'inventory' | 'finance' | 'hr' | 'reports' | 'settings'

interface NavItem {
  id: ViewId
  label: string
  icon: React.ReactNode
  badge?: string
  badgeTone?: string
}

const navSections: { title: string; items: NavItem[] }[] = [
  {
    title: 'Оперативная работа',
    items: [
      { id: 'dashboard', label: 'Дашборд', icon: <LayoutDashboard className="h-4 w-4" /> },
      { id: 'sales', label: 'Продажи', icon: <ShoppingCart className="h-4 w-4" />, badge: '46', badgeTone: 'bg-emerald-500' },
      { id: 'inventory', label: 'Склад', icon: <Boxes className="h-4 w-4" />, badge: '3', badgeTone: 'bg-red-500' },
    ],
  },
  {
    title: 'Области учёта',
    items: [
      { id: 'finance', label: 'Финансы', icon: <Banknote className="h-4 w-4" />, badge: '1', badgeTone: 'bg-amber-500' },
      { id: 'hr', label: 'Персонал', icon: <UsersRound className="h-4 w-4" /> },
      { id: 'reports', label: 'Отчёты', icon: <FileBarChart2 className="h-4 w-4" /> },
    ],
  },
  {
    title: 'Система',
    items: [
      { id: 'settings', label: 'Настройки', icon: <Settings className="h-4 w-4" /> },
    ],
  },
]

const viewTitles: Record<ViewId, { title: string; crumb: string }> = {
  dashboard: { title: 'Дашборд', crumb: 'Обзор компании' },
  sales: { title: 'Продажи', crumb: 'Заказы клиентов' },
  inventory: { title: 'Склад', crumb: 'Остатки и движения' },
  finance: { title: 'Финансы', crumb: 'Счета и платежи' },
  hr: { title: 'Персонал', crumb: 'Сотрудники и отделы' },
  reports: { title: 'Отчёты', crumb: 'Аналитика' },
  settings: { title: 'Настройки', crumb: 'Параметры системы' },
}

function Logo({ compact = false }: { compact?: boolean }) {
  return (
    <div className="flex items-center gap-2.5">
      <span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-emerald-500 font-bold text-white shadow-sm">
        Т
      </span>
      {!compact && (
        <div className="leading-tight">
          <p className="text-sm font-bold tracking-tight text-white">ТехноПром</p>
          <p className="text-[11px] text-zinc-400">ERP · макет v0.9</p>
        </div>
      )}
    </div>
  )
}

function SidebarNav({ current, onNavigate }: { current: ViewId; onNavigate: (v: ViewId) => void }) {
  return (
    <nav className="min-h-0 flex-1 space-y-4 overflow-y-auto px-3 py-3 erp-scroll" aria-label="Основная навигация">
      {navSections.map((section) => (
        <div key={section.title}>
          <p className="mb-1.5 px-3 text-[11px] font-semibold uppercase tracking-wider text-zinc-500">
            {section.title}
          </p>
          <div className="space-y-0.5">
            {section.items.map((item) => {
              const active = current === item.id
              return (
                <button
                  key={item.id}
                  onClick={() => onNavigate(item.id)}
                  aria-current={active ? 'page' : undefined}
                  className={cn(
                    'group flex w-full items-center gap-3 rounded-lg px-3 py-2 text-sm font-medium transition-colors',
                    active
                      ? 'bg-emerald-500/15 text-emerald-300'
                      : 'text-zinc-400 hover:bg-zinc-800/60 hover:text-zinc-100'
                  )}
                >
                  <span className={cn('transition-colors', active ? 'text-emerald-400' : 'text-zinc-500 group-hover:text-zinc-300')}>
                    {item.icon}
                  </span>
                  <span className="flex-1 text-left">{item.label}</span>
                  {item.badge && (
                    <span className={cn(
                      'flex h-5 min-w-5 items-center justify-center rounded-full px-1.5 text-[11px] font-bold text-white',
                      item.badgeTone
                    )}>
                      {item.badge}
                    </span>
                  )}
                </button>
              )
            })}
          </div>
        </div>
      ))}
    </nav>
  )
}

function SidebarFooter() {
  return (
    <div className="border-t border-zinc-800 p-3">
      <div className="rounded-xl bg-gradient-to-br from-zinc-800 to-zinc-900 p-3">
        <p className="flex items-center gap-1.5 text-xs font-semibold text-zinc-100">
          <PenTool className="h-3.5 w-3.5 shrink-0 text-emerald-400" /> Это макет интерфейса
        </p>
        <p className="mt-1 text-[11px] leading-snug text-zinc-400">
          Набросок ERP: демо-данные и нереальные суммы.
        </p>
      </div>
    </div>
  )
}

export function ErpShell({ onLogout }: { onLogout?: () => void }) {
  const [view, setView] = useState<ViewId>('dashboard')
  const [mobileOpen, setMobileOpen] = useState(false)
  const [paletteOpen, setPaletteOpen] = useState(false)
  const [profileOpen, setProfileOpen] = useState(false)
  const [shareOpen, setShareOpen] = useState(false)
  const { theme, setTheme } = useTheme()

  // hydration-safe флаг «смонтировано на клиенте» (без setState в эффекте)
  const emptySubscribe = () => () => {}
  const mounted = useSyncExternalStore(
    emptySubscribe,
    () => true,
    () => false
  )

  const navigate = (v: ViewId) => {
    setView(v)
    setMobileOpen(false)
  }

  const logout = () => {
    try {
      window.localStorage.removeItem('erp-demo-auth')
    } catch {
      /* noop */
    }
    onLogout?.()
  }

  const renderView = () => {
    switch (view) {
      case 'dashboard': return <DashboardView onOpenFinance={() => navigate('finance')} />
      case 'sales': return <SalesView />
      case 'inventory': return <InventoryView />
      case 'finance': return <FinanceView />
      case 'hr': return <HrView />
      case 'reports': return <ReportsView />
      case 'settings': return <SettingsView />
    }
  }

  return (
    <div className="flex min-h-screen bg-background">
      <CommandPalette
        open={paletteOpen}
        onOpenChange={setPaletteOpen}
        onNavigate={navigate}
        onOpenProfile={() => setProfileOpen(true)}
        onOpenShare={() => setShareOpen(true)}
      />
      <UserProfileDialog open={profileOpen} onOpenChange={setProfileOpen} onLogout={logout} />
      <ShareDialog open={shareOpen} onOpenChange={setShareOpen} />
      {/* Десктопный сайдбар */}
      <aside className="fixed inset-y-0 left-0 z-40 hidden w-64 flex-col bg-zinc-900 lg:flex print:hidden">
        <div className="flex h-16 items-center border-b border-zinc-800 px-5">
          <Logo />
        </div>
        <SidebarNav current={view} onNavigate={navigate} />
        <SidebarFooter />
      </aside>

      {/* Основная область */}
      <div className="flex min-h-screen w-full flex-col lg:pl-64">
        {/* Шапка */}
        <header className="sticky top-0 z-30 flex h-16 items-center gap-2 border-b border-zinc-200 bg-background/95 px-4 backdrop-blur supports-[backdrop-filter]:bg-background/80 sm:gap-3 sm:px-6 dark:border-zinc-800 print:hidden">
          {/* Мобильное меню */}
          <Sheet open={mobileOpen} onOpenChange={setMobileOpen}>
            <SheetTrigger asChild>
              <Button variant="outline" size="icon" className="h-9 w-9 lg:hidden" aria-label="Открыть меню">
                <Menu className="h-4 w-4" />
              </Button>
            </SheetTrigger>
            <SheetContent side="left" className="w-72 border-0 bg-zinc-900 p-0">
              <SheetTitle className="sr-only">Навигация по разделам</SheetTitle>
              <div className="flex h-16 items-center border-b border-zinc-800 px-5">
                <Logo />
              </div>
              <SidebarNav current={view} onNavigate={navigate} />
              <SidebarFooter />
            </SheetContent>
          </Sheet>

          {/* Хлебные крошки / заголовок */}
          <div className="min-w-0 flex-1">
            <p className="truncate text-sm font-semibold text-foreground">
              {viewTitles[view].title}
              <span className="ml-2 hidden font-normal text-muted-foreground sm:inline">· {viewTitles[view].crumb}</span>
            </p>
          </div>

          {/* Поиск (открывает палитру Ctrl+K) */}
          <button
            onClick={() => setPaletteOpen(true)}
            className="hidden h-9 w-56 items-center gap-2 rounded-full border border-transparent bg-zinc-100 px-3 text-sm text-muted-foreground transition-colors hover:border-zinc-200 hover:bg-zinc-50 lg:flex lg:w-64 dark:bg-zinc-800/70 dark:hover:bg-zinc-800 dark:hover:border-zinc-700"
            aria-label="Открыть поиск (Ctrl+K)"
          >
            <Search className="h-4 w-4 shrink-0" />
            <span className="flex-1 text-left">Поиск по ERP…</span>
            <kbd className="rounded border border-zinc-200 bg-white px-1.5 py-0.5 text-[10px] font-semibold text-zinc-500 dark:border-zinc-700 dark:bg-zinc-900 dark:text-zinc-400">
              Ctrl K
            </kbd>
          </button>
          <Button
            variant="outline"
            size="icon"
            className="h-9 w-9 md:hidden"
            onClick={() => setPaletteOpen(true)}
            aria-label="Поиск"
          >
            <Search className="h-4 w-4" />
          </Button>

          {/* Переключатель темы */}
          <Button
            variant="outline"
            size="icon"
            className="h-9 w-9"
            onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')}
            aria-label={mounted && theme === 'dark' ? 'Включить светлую тему' : 'Включить тёмную тему'}
            title={mounted && theme === 'dark' ? 'Светлая тема' : 'Тёмная тема'}
          >
            {mounted && theme === 'dark' ? <Sun className="h-4 w-4" /> : <Moon className="h-4 w-4" />}
          </Button>

          {/* Поделиться макетом */}
          <Button
            variant="outline"
            size="icon"
            className="h-9 w-9"
            onClick={() => setShareOpen(true)}
            aria-label="Поделиться макетом"
            title="Поделиться макетом"
          >
            <Share2 className="h-4 w-4" />
          </Button>

          {/* Центр уведомлений */}
          <NotificationCenter
            onNavigate={(v: ErpNotification['view']) => navigate(v)}
          />

          {/* Помощь */}
          <Button variant="outline" size="icon" className="hidden h-9 w-9 sm:inline-flex" aria-label="Помощь">
            <HelpCircle className="h-4 w-4" />
          </Button>

          {/* Профиль */}
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <button
                className="flex items-center gap-2 rounded-full border border-zinc-200 bg-white py-1 pl-1 pr-2.5 transition-colors hover:bg-zinc-50 dark:border-zinc-700 dark:bg-zinc-900 dark:hover:bg-zinc-800"
                aria-label="Меню пользователя"
              >
                <Avatar className="h-7 w-7">
                  <AvatarFallback className="bg-emerald-100 text-xs font-bold text-emerald-700">ВН</AvatarFallback>
                </Avatar>
                <span className="hidden text-sm font-medium sm:inline">В. Науменко</span>
                <ChevronsUpDown className="h-3.5 w-3.5 text-muted-foreground" />
              </button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end" className="w-52">
              <DropdownMenuLabel>
                <p>Науменко Владимир</p>
                <p className="text-xs font-normal text-muted-foreground">v.naumenko@technoprom.ru</p>
              </DropdownMenuLabel>
              <DropdownMenuSeparator />
              <DropdownMenuItem onClick={() => setPaletteOpen(true)}>
                <Search className="mr-2 h-4 w-4" /> Поиск (Ctrl+K)
              </DropdownMenuItem>
              <DropdownMenuItem
                onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')}
              >
                {mounted && theme === 'dark' ? (
                  <><Sun className="mr-2 h-4 w-4" /> Светлая тема</>
                ) : (
                  <><Moon className="mr-2 h-4 w-4" /> Тёмная тема</>
                )}
              </DropdownMenuItem>
              <DropdownMenuItem onClick={() => setProfileOpen(true)}>
                <UserCog className="mr-2 h-4 w-4" /> Профиль и роли
              </DropdownMenuItem>
              <DropdownMenuItem onClick={() => setShareOpen(true)}>
                <Share2 className="mr-2 h-4 w-4" /> Поделиться макетом
              </DropdownMenuItem>
              <DropdownMenuSeparator />
              <DropdownMenuItem className="text-red-600 focus:text-red-600" onClick={logout}>
                <LogOut className="mr-2 h-4 w-4" /> Выйти
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </header>

        {/* Контент */}
        <main className="flex-1 px-4 py-6 sm:px-6 lg:px-8">
          <div className="mx-auto w-full max-w-[1400px]">
            <motion.div
              key={view}
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.22, ease: 'easeOut' }}
            >
              {renderView()}
            </motion.div>
          </div>
        </main>

        {/* Липкий футер */}
        <footer className="mt-auto border-t border-zinc-200 bg-background px-4 py-4 sm:px-6 lg:px-8 dark:border-zinc-800">
          <div className="mx-auto flex w-full max-w-[1400px] flex-col items-center justify-between gap-2 text-xs text-muted-foreground sm:flex-row">
            <p>
              © 2025 ООО «ТехноПром» · ERP-макет интерфейса · <span className="font-medium text-emerald-700 dark:text-emerald-400">демо-данные</span>
            </p>
            <div className="flex items-center gap-4">
              <span>Сборка v0.9.0</span>
              <Separator orientation="vertical" className="hidden h-3 sm:block" />
              <span>БД: 12 483 записи</span>
              <Separator orientation="vertical" className="hidden h-3 sm:block" />
              <span className="flex items-center gap-1.5">
                <span className="h-2 w-2 animate-pulse rounded-full bg-emerald-500" /> Все сервисы работают
              </span>
            </div>
          </div>
        </footer>
      </div>
    </div>
  )
}

// frontend/src/layouts/ErpShell.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { useRoute, useRouter } from 'vue-router'
import {
  Menu, Sun, Moon, LogOut, KeyRound, ChevronsUpDown, Plug, Bot, Settings2, LayoutDashboard,
} from 'lucide-vue-next'
import { get, post } from '../api/client'
import { useAuthStore } from '../stores/auth'
import { Avatar, Button, Dialog, DropdownMenu, DropdownMenuItem, Input, Label, ToastHost, useToast } from '../components/ui'
import ChangePasswordDialog from './ChangePasswordDialog.vue'

const { t } = useI18n()
const route = useRoute()
const router = useRouter()
const auth = useAuthStore()
const toast = useToast()

// ---------- Тема (§3: .dark на <html>, localStorage, 0.25s) ----------
const THEME_KEY = 'erp-theme'
const theme = ref<'light' | 'dark'>(
  (localStorage.getItem(THEME_KEY) as 'light' | 'dark') ?? 'light',
)
watch(theme, (value) => {
  document.documentElement.classList.toggle('dark', value === 'dark')
  localStorage.setItem(THEME_KEY, value)
}, { immediate: true })
function toggleTheme() {
  theme.value = theme.value === 'dark' ? 'light' : 'dark'
}

// ---------- Навигация (§5; фильтрация по правам — этап C) ----------
// В этапе A показываем только живые разделы; Дашборд/Продажи/Финансы/Отчёты
// включаются своими этапами (D/E/F), склад/персонал — после бэкенда (ADR-007).
const navSections = computed(() => [
  {
    title: t('nav.sections.system'),
    items: [
      { to: '/integrations/connections', label: t('nav.integrations'), icon: Plug },
      { to: '/assistant', label: t('nav.assistant'), icon: Bot },
      { to: '/settings/system', label: t('nav.settings'), icon: Settings2 },
    ],
  },
].filter((section) => section.items.length > 0))

const pageTitle = computed(() => (route.meta.title as string) ?? '')
const pageCrumb = computed(() => (route.meta.crumb as string) ?? '')

function isActive(to: string): boolean {
  return route.path === to || route.path.startsWith(`${to}/`)
}

// ---------- Организация (подпись под логотипом, §5) ----------
const orgName = ref('')
onMounted(async () => {
  try {
    const companies = await get<Array<{ name: string }>>('/companies')
    orgName.value = companies[0]?.name ?? ''
  } catch {
    orgName.value = ''
  }
})

// ---------- Мобильный drawer (§5, < lg) ----------
const mobileOpen = ref(false)
watch(() => route.path, () => { mobileOpen.value = false })

// ---------- Футер: версия + /health (§5) ----------
const health = ref<'ok' | 'fail' | 'pending'>('pending')
let healthTimer: number | null = null
async function checkHealth() {
  try {
    const response = await fetch('/health')
    health.value = response.ok ? 'ok' : 'fail'
  } catch {
    health.value = 'fail'
  }
}
onMounted(() => {
  checkHealth()
  healthTimer = window.setInterval(checkHealth, 60_000)
})
onBeforeUnmount(() => { if (healthTimer !== null) window.clearInterval(healthTimer) })

// ---------- Профиль: смена пароля + выход ----------
const passwordOpen = ref(false)
async function logout() {
  await auth.apiLogout()
  auth.logout()
  router.push({ name: 'login' })
}
</script>

<template>
  <div class="flex min-h-screen bg-background">
    <!-- Сайдбар: десктоп -->
    <aside class="fixed inset-y-0 left-0 z-40 hidden w-64 flex-col bg-zinc-900 lg:flex print:hidden">
      <div class="flex h-16 shrink-0 items-center border-b border-zinc-800 px-5">
        <div class="flex items-center gap-2.5">
          <span class="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-emerald-500 text-lg font-bold text-white shadow-sm">К</span>
          <div class="leading-tight">
            <p class="text-sm font-bold tracking-tight text-white">{{ t('brand.name') }}</p>
            <p class="truncate text-[11px] text-zinc-400" :title="orgName">
              {{ orgName || t('brand.tagline') }}
            </p>
          </div>
        </div>
      </div>
      <nav class="min-h-0 flex-1 space-y-4 overflow-y-auto px-3 py-3 erp-scroll" aria-label="Основная навигация">
        <div v-for="section in navSections" :key="section.title">
          <p class="mb-1.5 px-3 text-[11px] font-semibold uppercase tracking-wider text-zinc-500">{{ section.title }}</p>
          <div class="space-y-0.5">
            <router-link
              v-for="item in section.items"
              :key="item.to"
              :to="item.to"
              :aria-current="isActive(item.to) ? 'page' : undefined"
              class="group flex w-full items-center gap-3 rounded-lg px-3 py-2 text-sm font-medium transition-colors"
              :class="isActive(item.to)
                ? 'bg-emerald-500/15 text-emerald-300'
                : 'text-zinc-400 hover:bg-zinc-800/60 hover:text-zinc-100'"
            >
              <component :is="item.icon" class="h-4 w-4 shrink-0" :class="isActive(item.to) ? 'text-emerald-400' : 'text-zinc-500 group-hover:text-zinc-300'" />
              <span class="flex-1 text-left">{{ item.label }}</span>
            </router-link>
          </div>
        </div>
      </nav>
      <div class="border-t border-zinc-800 p-3 text-[11px] leading-snug text-zinc-500">
        {{ t('shell.sidebarNote') }}
      </div>
    </aside>

    <!-- Сайдбар: мобильный drawer -->
    <Teleport to="body">
      <div v-if="mobileOpen" class="fixed inset-0 z-50 lg:hidden">
        <div class="absolute inset-0 bg-black/50" @click="mobileOpen = false" />
        <aside class="absolute inset-y-0 left-0 flex w-72 flex-col bg-zinc-900">
          <div class="flex h-16 items-center border-b border-zinc-800 px-5">
            <div class="flex items-center gap-2.5">
              <span class="flex h-9 w-9 items-center justify-center rounded-lg bg-emerald-500 text-lg font-bold text-white">К</span>
              <div class="leading-tight">
                <p class="text-sm font-bold text-white">{{ t('brand.name') }}</p>
                <p class="truncate text-[11px] text-zinc-400 max-w-40">{{ orgName || t('brand.tagline') }}</p>
              </div>
            </div>
          </div>
          <nav class="flex-1 overflow-y-auto px-3 py-3 erp-scroll" aria-label="Мобильная навигация">
            <div v-for="section in navSections" :key="section.title" class="mb-4">
              <p class="mb-1.5 px-3 text-[11px] font-semibold uppercase tracking-wider text-zinc-500">{{ section.title }}</p>
              <router-link
                v-for="item in section.items"
                :key="item.to"
                :to="item.to"
                class="group flex w-full items-center gap-3 rounded-lg px-3 py-2 text-sm font-medium"
                :class="isActive(item.to) ? 'bg-emerald-500/15 text-emerald-300' : 'text-zinc-400 hover:bg-zinc-800/60 hover:text-zinc-100'"
              >
                <component :is="item.icon" class="h-4 w-4" />
                {{ item.label }}
              </router-link>
            </div>
          </nav>
        </aside>
      </div>
    </Teleport>

    <!-- Основная область -->
    <div class="flex min-h-screen w-full flex-col lg:pl-64">
      <!-- Шапка -->
      <header class="sticky top-0 z-30 flex h-16 items-center gap-2 border-b border-zinc-200 bg-background/95 px-4 backdrop-blur supports-[backdrop-filter]:bg-background/80 sm:gap-3 sm:px-6 dark:border-zinc-800 print:hidden">
        <Button variant="outline" size="icon" class="h-9 w-9 lg:hidden" :aria-label="t('shell.openMenu')" @click="mobileOpen = true">
          <Menu class="h-4 w-4" />
        </Button>
        <div class="min-w-0 flex-1">
          <p class="truncate text-sm font-semibold text-foreground">
            {{ pageTitle }}
            <span v-if="pageCrumb" class="ml-2 hidden font-normal text-muted-foreground sm:inline">· {{ pageCrumb }}</span>
          </p>
        </div>
        <Button variant="outline" size="icon" class="h-9 w-9" :aria-label="theme === 'dark' ? t('shell.themeLight') : t('shell.themeDark')" @click="toggleTheme">
          <Sun v-if="theme === 'dark'" class="h-4 w-4" />
          <Moon v-else class="h-4 w-4" />
        </Button>
        <DropdownMenu align="end">
          <template #trigger>
            <span class="flex items-center gap-2 rounded-full border border-zinc-200 bg-card py-1 pl-1 pr-2.5 transition-colors hover:bg-zinc-50 dark:border-zinc-700 dark:bg-zinc-900 dark:hover:bg-zinc-800" :aria-label="t('shell.userMenu')">
              <Avatar :initials="auth.userName.slice(0, 2).toUpperCase()" />
              <span class="hidden max-w-32 truncate text-sm font-medium sm:inline">{{ auth.userName }}</span>
              <ChevronsUpDown class="h-3.5 w-3.5 text-muted-foreground" />
            </span>
          </template>
          <template #label>
            <p class="font-medium">{{ auth.userName }}</p>
            <p class="text-xs font-normal text-muted-foreground">{{ t(`roles.${auth.user?.role ?? 'user'}`) }}</p>
          </template>
          <DropdownMenuItem @click="passwordOpen = true">
            <KeyRound class="h-4 w-4" /> {{ t('shell.changePassword') }}
          </DropdownMenuItem>
          <DropdownMenuItem destructive @click="logout">
            <LogOut class="h-4 w-4" /> {{ t('shell.logout') }}
          </DropdownMenuItem>
        </DropdownMenu>
      </header>

      <!-- Контент (появление экрана 0.22s) -->
      <main class="flex-1 px-4 py-6 sm:px-6 lg:px-8">
        <div class="mx-auto w-full max-w-[1400px]">
          <router-view :key="route.path" class="erp-view-in" />
        </div>
      </main>

      <!-- Футер: версия + статус сервисов -->
      <footer class="mt-auto border-t border-zinc-200 bg-background px-4 py-4 sm:px-6 lg:px-8 dark:border-zinc-800 print:hidden">
        <div class="mx-auto flex w-full max-w-[1400px] flex-col items-center justify-between gap-2 text-xs text-muted-foreground sm:flex-row">
          <p>{{ t('brand.name') }} · {{ t('shell.copyright') }}</p>
          <div class="flex items-center gap-4">
            <span>{{ t('shell.build') }} v0.2.0</span>
            <span class="flex items-center gap-1.5">
              <span class="h-2 w-2 animate-pulse rounded-full" :class="health === 'ok' ? 'bg-emerald-500' : health === 'fail' ? 'bg-red-500' : 'bg-zinc-400'" />
              {{ health === 'ok' ? t('shell.servicesOk') : health === 'fail' ? t('shell.servicesFail') : t('shell.servicesPending') }}
            </span>
          </div>
        </div>
      </footer>
    </div>

    <ChangePasswordDialog v-model="passwordOpen" />
    <ToastHost />
  </div>
</template>
